name: basic checks

on:
  push:

jobs:
  check_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "latest"
          enable-stack: true
      - name: build
        run: make
      - name: check binary name
        run: test -f glados
