name: basic checks

on:
  push:

jobs:
  check_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: build
        run: make
      - name: check binary name
        run: test -f glados
